blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/KiaArmani/fabfilter/blob/main/README.md
    about: Read the documentation for installation and usage instructions